[package]
name = "Rust_Controller"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32.3"
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
differential-evolution = "0.2.2"
rayon = "1.8.1"